backend_resource_group_name = "rg-opera-terraform-state"
backend_container_name = "tfstate"
backend_storage_account_name = "backendstorageopera"
resource_group_name = "rg-opera-terraform-main"
location = "westeurope"
subscription_id   = "c07d12e1-5880-4a69-837d-8004c99145fc"