name: Terraform Deployment Workflow

on:
  push:
    branches:
      - "dev"
      - "staging"
      - "prod"
  pull_request:
    branches:
      - "main"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10  # Update to your Terraform version if needed

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./deployments

      # Select the appropriate environment
      - name: Select Environment and Plan
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            terraform plan -var-file="dev.tfvars"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            terraform plan -var-file="staging.tfvars"
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            terraform plan -var-file="prod.tfvars"
          else
            echo "Branch not recognized for environment"
            exit 1
          fi
        working-directory: ./deployments

      # Apply if dev or staging branch (main branch requires manual approval)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging'
        run: |
          terraform apply -auto-approve -var-file="${{ github.ref_name }}.tfvars"
        working-directory: ./deployments