name: 'Terraform Deployment'

on:
  push:
    branches:
      - 'dev'
      - 'staging'
      - 'prod'

jobs:
  deploy:
    name: 'Terraform Deploy'
    if: github.ref_name != 'prod'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}  # Use dynamic environments for non-prod branches

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Init'
        run: terraform init -backend-config="backend.${{ github.ref_name }}.conf"
        working-directory: ./deployments

      - name: 'Terraform Plan'
        run: terraform plan -var-file="${{ github.ref_name }}.tfvars"
        working-directory: ./deployments

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -var-file="${{ github.ref_name }}.tfvars"
        working-directory: ./deployments

  deploy_prod:
    name: 'Terraform Deploy to Production'
    if: github.ref_name == 'prod'
    runs-on: ubuntu-latest
    environment:
      name: production

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Init'
        run: terraform init -backend-config="backend.prod.conf"
        working-directory: ./deployments

      - name: 'Terraform Plan'
        run: terraform plan -var-file="prod.tfvars"
        working-directory: ./deployments

          # This step will pause until manual approval is given due to environment protection rules

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -var-file="prod.tfvars"
        working-directory: ./deployments