name: Terraform Destroy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev, staging, prod)"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init -backend-config="backend.${{ github.event.inputs.environment }}.conf"
        working-directory: ./deployments

      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
        working-directory: ./deployments
