name: 'Terraform Pull Request Checks'

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'staging'
      - 'prod'

jobs:
  terraform:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Format Check'
        run: terraform fmt -check -recursive

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Lint'
        uses: terraform-linters/tflint-action@v3.6.0

      - name: 'Terraform Security Scan'
        uses: aquasecurity/tfsec-action@v1.4.0
