name: 'Terraform Pull Request Checks'

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'staging'
      - 'prod'

jobs:
  terraform:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Format Check'
        run: terraform fmt -check -recursive

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Set up TFLint'
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.46.0  # Specify the version of TFLint you want to use

      - name: 'Trivy Scan'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          severity: "HIGH,CRITICAL"
          scan-ref: "."